name: Generate and Deploy DartDoc

on:
  push:
    branches:
      - main  # Set to your default branch

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Dart
      uses: dart-lang/setup-dart@v1

    - name: Install DartDoc
      run: dart pub global activate dartdoc

    - name: Generate Documentation
      run: dart pub global run dartdoc

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc  # Directory where dartdoc outputs documentation
